### ISSUE TITLE
Add DCNv2 Plugin with TensorRT 8.x

### ISSUE THREAD

**Issue by nhatanh174** [CaoWGG/TensorRT-CenterNet#103]
Hi,
Thanks so much for your code.
I added successfully DCNv2 plugin into TensorRT 7.x. However, when I tried your code with tensorRT 8.x and builded TensorRT OSS again, the process can't complete.  It shows these errors:

**Error:** 
/workspace/TensorRT/include/NvInferRuntimeCommon.h:931:24: error:   overriding 'virtual nvinfer1::IPluginV2* nvinfer1::IPluginCreator::deserializePlugin(const AsciiChar*, const void*, size_t) noexcept'
     virtual IPluginV2* deserializePlugin(AsciiChar const* name, void const* serialData, size_t serialLength) noexcept = 0;
                        ^~~~~~~~~~~~~~~~~
/workspace/TensorRT/plugin/DCNv2/DCNv2.cpp: In member function 'virtual bool nvinfer1::plugin::DCNv2Plugin::supportsFormatCombination(int, const nvinfer1::PluginTensorDesc*, int, int)':
/workspace/TensorRT/plugin/DCNv2/DCNv2.cpp:115:107: error: 'kNCHW' is not a member of 'nvinfer1::TensorFormat'
   return (inOut[pos].type == nvinfer1::DataType::kFLOAT) && (inOut[pos].format == nvinfer1::TensorFormat::kNCHW);
                                                                                                           ^~~~~
/workspace/TensorRT/plugin/DCNv2/DCNv2.cpp: In member function 'virtual bool nvinfer1::plugin::DCNv2Plugin::supportsFormatCombination(int, const nvinfer1::PluginTensorDesc*, int, int)':
/workspace/TensorRT/plugin/DCNv2/DCNv2.cpp:115:107: error: 'kNCHW' is not a member of 'nvinfer1::TensorFormat'
   return (inOut[pos].type == nvinfer1::DataType::kFLOAT) && (inOut[pos].format == nvinfer1::TensorFormat::kNCHW);
                                                                                                           ^~~~~
plugin/CMakeFiles/nvinfer_plugin.dir/build.make:62: recipe for target 'plugin/CMakeFiles/nvinfer_plugin.dir/DCNv2/DCNv2.cpp.o' failed

**My environment:**
- TensorRT: 8.0.3.4
- Ubuntu 18.04
-  Cuda version: 11.3

Any idea how to solute this issue ? 
Thanks.

**Comment by ZhangdamiaoCN** [comment]
@nhatanh174 hello, I was trying to run this project under TensorRT 7.x, but failed. Could you please tell me the specific implementation process? I ran into this problem: ERROR: INVALID ARGUMENT: getPlugincreator could not find plugin DCNv2 version 1

**Comment by nhatanh174** [comment]
Hi,
You can follow this instruction to add DCNv2 plugin to TensorRT 7.x.
https://github.com/lesliejackson/TensorRT-DCNv2-Plugin
Good luck guys,
Anh Nguyen

Vào Th 6, 10 thg 12, 2021 vào lúc 19:51 ZhangdamiaoCN <
***@***.***> đã viết:

**Comment by nhatanh174** [comment]
@ZhangdamiaoCN  
You can follow this instruction to add DCNv2 plugin to TensorRT 7.x.
https://github.com/lesliejackson/TensorRT-DCNv2-Plugin

**Comment by sainttelant** [comment]
@nhatanh174  hi, have you solved the compatibility issue of Tensorrt 8.2 and dcnv2? it is so annoying

**Comment by sainttelant** [comment]
@nhatanh174   /workspace/TensorRT/include/NvInferRuntimeCommon.h:931:24: error: overriding 'virtual nvinfer1::IPluginV2* nvinfer1::IPluginCreator::deserializePlugin(const AsciiChar*, const void*, size_t) noexcept'
virtual IPluginV2* deserializePlugin(AsciiChar const* name, void const* serialData, size_t serialLength) noexcept = 0;
^~~~~~~~~~~~~~~~~
/workspace/TensorRT/plugin/DCNv2/DCNv2.cpp: In member function 'virtual bool nvinfer1::plugin::DCNv2Plugin::supportsFormatCombination(int, const nvinfer1::PluginTensorDesc*, int, int)':
/workspace/TensorRT/plugin/DCNv2/DCNv2.cpp:115:107: error: 'kNCHW' is not a member of 'nvinfer1::TensorFormat'
return (inOut[pos].type == nvinfer1::DataType::kFLOAT) && (inOut[pos].format == nvinfer1::TensorFormat::kNCHW);
^~~~~


by the way. i know these issues are caused by function declaration mismatch problems, you just need to add "noexcept" in your function declaration and definition respectively, that will be worked
